version: '3'
services:
  mysql:
    image: mysql:8.3.0
    hostname: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - loja
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/mysql/data
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  loja_simulada:
    buld:
      context: ./loja_simulada
    image: loja_simulada_image
    hostname: loja_simulada
    container_name: loja_simulada
    ports:
      - '30001:30001'
    networks:
      - loja
    environment:
      LOJA_SIMULADA_PORTA: 30001
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: vendas
      KAFKA_BROKERCONNECT: 'kafka:19092'
    command: npm run start
    restart: always
    depends_on:
      - mysql
      # - kafka
    links:
      - mysql
      # - kafka
