version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - loja
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./kafka/data/zookeeper/data:/data
      - ./kafka/data/zookeeper/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
    expose:
      - '9092'
    networks:
      - loja
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka/data/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: 'no'
    ports:
      - '9000:9000'
    networks:
      - loja
    environment:
      KAFKA_BROKERCONNECT: 'kafka:19092'
    depends_on:
      - kafka
  mysql:
    image: mysql:8.3.0
    hostname: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysql', '-h127.0.0.1', '-P3306', '-uroot', '-proot']
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    expose:
      - '3306'
    networks:
      - loja
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/mysql/data
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  loja_simulada:
    image: loja_simulada_image
    build:
      context: loja_simulada
    hostname: loja_simulada
    container_name: loja_simulada
    ports:
      - '30001:30001'
    networks:
      - loja
    environment:
      LOJA_SIMULADA_PORTA: 30001
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: vendas
      KAFKA_BROKERCONNECT: 'kafka:19092'
    command: npm run start
    restart: always
    depends_on:
      - mysql:
        condition: service_healthy
      - kafka
    links:
      - mysql
      - kafka
networks:
  loja:
    driver: bridge
